language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  app: polar-tundra-83007
  api_key:
    secure: CT2NBPzIgD4Uw/StODq0cOnCH1c3OeNlhfl+4Q0CBUnfDoKdL5vOsa5Ffm22r389nUBZd1p0chBMKPoISkrQMhkEHi/RbwKnRincI9qh6iuasbnHFX4j4EpBXrCAVN8LaMdsU6CFtCM0UuglMfywQbdhE9TfsuvXKflN8lylpXfcLoCVeRv38QjLVx+yLbGYdm5pVCbR/SocgnGF7urccmkLtzqHSg+ANHjxlAEeMeB4AWr49hmUy0Zk68QzDNlJjq1JfPN2wFn25++vBPQpRuKI/B6YoNjp4dcp2BSTjG8JNmT+5n+AnebQOnNuc2nXn7XIjq1isoDsKzmVnpW+wHXAg0EJ2dKi4gmPAFvL+abhLAYov7S2dkO8qxfc0MoUhoLKft5KXQRjCeze4TkYClTpiiNcRTQuM0tZgrxfrEkXiaNdkxfpNI6tvsZrviRodvNZQ36MHz7WPquY0ijUrHEqvYC84itIwJg32A/tdtGDzUVzZkaxR0YFOIfIdD5I7V+/Nb6gN/8TVeSFQyYGjQvU/5oh2vYKlWVUJenFxL+s38FD9yxd6YDhGYO+blhcND7ZkKXPN9X6py6YE/cMyGEwQNKujkXK4ka+W1wfish2fB6TsMwlXy0jtzZf0gSIRHdqCckIQ5PzNxrXIYt+bGjeHvauaTePyFtSxffOJtc=
